import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "tailwind-config/styles";
import StoreProvider from "../providers/store-provider";
import "./globals.css";
import Wrapper from "./wrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ft_transgender",
  description: "Generated by khaliha ela molana team",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <StoreProvider>
          {/* <Wrapper></Wrapper> */}
          {children}
          
        </StoreProvider>
      </body>
    </html>
  );
}
