import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "tailwind-config/styles";
import AsideBar from "../layouts/shared-aside-bar/aside-bar";
import Header from "../layouts/shared-haeder/header";
import StoreProvider from "../providers/store-provider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ft_transgender",
  description: "Generated by khaliha ela molana team",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          {/* {children} */}
          <Header />
          <AsideBar />
          </StoreProvider>
      </body>
    </html>
  );
}
