import type { Metadata } from "next";
import { Inter } from "next/font/google";
import 'tailwind-config/styles'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ft_transgender",
  description: "Generated by khaliha ela molana team",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
